# Generated by Django 5.0.6 on 2024-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
