# Generated by Django 5.0.6 on 2024-05-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
