# Generated by Django 5.0.6 on 2024-05-22 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_favoritos_favoritos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favoritos',
            field=models.ManyToManyField(null=True, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favoritos',
        ),
    ]
