# Generated by Django 5.0.6 on 2024-05-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='motivo',
            field=models.TextField(null=True, verbose_name='Motivo'),
        ),
    ]
